-- USER SQL
CREATE USER DEMOUSER IDENTIFIED BY phaifei7Joon6vae;

-- ADD ROLES
GRANT CONNECT TO DEMOUSER;
GRANT CONSOLE_DEVELOPER TO DEMOUSER;
GRANT DWROLE TO DEMOUSER;
GRANT GRAPH_DEVELOPER TO DEMOUSER;
GRANT OML_DEVELOPER TO DEMOUSER;
GRANT RESOURCE TO DEMOUSER;
ALTER USER DEMOUSER DEFAULT ROLE CONSOLE_DEVELOPER,DWROLE,GRAPH_DEVELOPER,OML_DEVELOPER;

-- REST ENABLE
BEGIN
    ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'DEMOUSER',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'demouser',
        p_auto_rest_auth=> TRUE
    );
    -- ENABLE DATA SHARING
    C##ADP$SERVICE.DBMS_SHARE.ENABLE_SCHEMA(
            SCHEMA_NAME => 'DEMOUSER',
            ENABLED => TRUE
    );
    commit;
END;
/

-- ENABLE GRAPH
ALTER USER DEMOUSER GRANT CONNECT THROUGH GRAPH$PROXY_USER;

-- ENABLE OML
ALTER USER DEMOUSER GRANT CONNECT THROUGH OML$PROXY;

-- QUOTA
ALTER USER DEMOUSER QUOTA UNLIMITED ON DATA;

