INSERT INTO products (code, description) VALUES ('LIV1001', '1984 - Annotated Edition - George Orwell');
INSERT INTO products (code, description) VALUES ('LIV1002', 'The Lord of the Rings - J.R.R. Tolkien');
INSERT INTO products (code, description) VALUES ('LIV1003', 'The Old Man and the Sea - Ernest Hemingway');
INSERT INTO products (code, description) VALUES ('LIV1004', 'To Kill a Mockingbird - Harper Lee');
INSERT INTO products (code, description) VALUES ('LIV1005', 'Pride and Prejudice - Jane Austen');
INSERT INTO products (code, description) VALUES ('LIV1006', 'Brave New World - Aldous Huxley');
INSERT INTO products (code, description) VALUES ('LIV1007', 'Animal Farm - George Orwell');
INSERT INTO products (code, description) VALUES ('LIV1008', 'Jane Eyre - Charlotte Brontë');
INSERT INTO products (code, description) VALUES ('LIV1009', 'Wuthering Heights - Emily Brontë');
INSERT INTO products (code, description) VALUES ('LIV1010', 'The Catcher in the Rye - J.D. Salinger');
INSERT INTO products (code, description) VALUES ('LIV1011', 'Fahrenheit 451 - Ray Bradbury');
INSERT INTO products (code, description) VALUES ('LIV1012', 'The Great Gatsby - F. Scott Fitzgerald');
INSERT INTO products (code, description) VALUES ('LIV1013', 'Moby-Dick - Herman Melville');
INSERT INTO products (code, description) VALUES ('LIV1014', 'War and Peace - Leo Tolstoy');
INSERT INTO products (code, description) VALUES ('LIV1015', 'Crime and Punishment - Fyodor Dostoevsky');
INSERT INTO products (code, description) VALUES ('LIV1016', 'The Brothers Karamazov - Fyodor Dostoevsky');
INSERT INTO products (code, description) VALUES ('LIV1017', 'Les Misérables - Victor Hugo');
INSERT INTO products (code, description) VALUES ('LIV1018', 'A Tale of Two Cities - Charles Dickens');
INSERT INTO products (code, description) VALUES ('LIV1019', 'Great Expectations - Charles Dickens');
INSERT INTO products (code, description) VALUES ('LIV1020', 'The Hobbit - J.R.R. Tolkien');
INSERT INTO products (code, description) VALUES ('LIV1021', 'The Alchemist - Paulo Coelho');
INSERT INTO products (code, description) VALUES ('LIV1022', 'The Da Vinci Code - Dan Brown');
INSERT INTO products (code, description) VALUES ('LIV1023', 'Angels & Demons - Dan Brown');
INSERT INTO products (code, description) VALUES ('LIV1024', 'Inferno - Dan Brown');
INSERT INTO products (code, description) VALUES ('LIV1025', 'Harry Potter and the Sorcerer s Stone - J.K. Rowling');
INSERT INTO products (code, description) VALUES ('LIV1026', 'Harry Potter and the Chamber of Secrets - J.K. Rowling');
INSERT INTO products (code, description) VALUES ('LIV1027', 'Harry Potter and the Prisoner of Azkaban - J.K. Rowling');
INSERT INTO products (code, description) VALUES ('LIV1028', 'Harry Potter and the Goblet of Fire - J.K. Rowling');
INSERT INTO products (code, description) VALUES ('LIV1029', 'Harry Potter and the Order of the Phoenix - J.K. Rowling');
INSERT INTO products (code, description) VALUES ('LIV1030', 'Harry Potter and the Half-Blood Prince - J.K. Rowling');
INSERT INTO products (code, description) VALUES ('LIV1031', 'Harry Potter and the Deathly Hallows - J.K. Rowling');
INSERT INTO products (code, description) VALUES ('LIV1032', 'The Picture of Dorian Gray - Oscar Wilde');
INSERT INTO products (code, description) VALUES ('LIV1033', 'Dracula - Bram Stoker');
INSERT INTO products (code, description) VALUES ('LIV1034', 'Frankenstein - Mary Shelley');
INSERT INTO products (code, description) VALUES ('LIV1035', 'The Metamorphosis - Franz Kafka');
INSERT INTO products (code, description) VALUES ('LIV1036', 'The Stranger - Albert Camus');
INSERT INTO products (code, description) VALUES ('LIV1037', 'The Trial - Franz Kafka');
INSERT INTO products (code, description) VALUES ('LIV1038', 'The Little Prince - Antoine de Saint-Exupéry');
INSERT INTO products (code, description) VALUES ('LIV1039', 'Don Quixote - Miguel de Cervantes');
INSERT INTO products (code, description) VALUES ('LIV1040', 'Ulysses - James Joyce');
INSERT INTO products (code, description) VALUES ('LIV1041', 'A Clockwork Orange - Anthony Burgess');
INSERT INTO products (code, description) VALUES ('LIV1042', 'Lolita - Vladimir Nabokov');
INSERT INTO products (code, description) VALUES ('LIV1043', 'Beloved - Toni Morrison');
INSERT INTO products (code, description) VALUES ('LIV1044', 'The Handmaid s Tale - Margaret Atwood');
INSERT INTO products (code, description) VALUES ('LIV1045', 'The Road - Cormac McCarthy');
INSERT INTO products (code, description) VALUES ('LIV1046', 'The Kite Runner - Khaled Hosseini');
INSERT INTO products (code, description) VALUES ('LIV1047', 'A Thousand Splendid Suns - Khaled Hosseini');
INSERT INTO products (code, description) VALUES ('LIV1048', 'Life of Pi - Yann Martel');
INSERT INTO products (code, description) VALUES ('LIV1049', 'The Book Thief - Markus Zusak');
INSERT INTO products (code, description) VALUES ('LIV1050', 'The Girl on the Train - Paula Hawkins');
INSERT INTO products (code, description) VALUES ('LIV1051', 'Gone Girl - Gillian Flynn');
INSERT INTO products (code, description) VALUES ('LIV1052', 'The Silent Patient - Alex Michaelides');
INSERT INTO products (code, description) VALUES ('LIV1053', 'Where the Crawdads Sing - Delia Owens');
INSERT INTO products (code, description) VALUES ('LIV1054', 'Verity - Colleen Hoover');
INSERT INTO products (code, description) VALUES ('LIV1055', 'It Ends With Us - Colleen Hoover');
INSERT INTO products (code, description) VALUES ('LIV1056', 'It Starts With Us - Colleen Hoover');
INSERT INTO products (code, description) VALUES ('LIV1057', 'Reminders of Him - Colleen Hoover');
INSERT INTO products (code, description) VALUES ('LIV1058', 'Ugly Love - Colleen Hoover');
INSERT INTO products (code, description) VALUES ('LIV1059', 'The Midnight Library - Matt Haig');
INSERT INTO products (code, description) VALUES ('LIV1060', 'The Seven Husbands of Evelyn Hugo - Taylor Jenkins Reid');
INSERT INTO products (code, description) VALUES ('LIV1061', 'Daisy Jones & The Six - Taylor Jenkins Reid');
INSERT INTO products (code, description) VALUES ('LIV1062', 'Malibu Rising - Taylor Jenkins Reid');
INSERT INTO products (code, description) VALUES ('LIV1063', 'Carrie Soto is Back - Taylor Jenkins Reid');
INSERT INTO products (code, description) VALUES ('LIV1064', 'The Night Circus - Erin Morgenstern');
INSERT INTO products (code, description) VALUES ('LIV1065', 'The House in the Cerulean Sea - TJ Klune');
INSERT INTO products (code, description) VALUES ('LIV1066', 'Under the Whispering Door - TJ Klune');
INSERT INTO products (code, description) VALUES ('LIV1067', 'Cloud Atlas - David Mitchell');
INSERT INTO products (code, description) VALUES ('LIV1068', 'The Shadow of the Wind - Carlos Ruiz Zafón');
INSERT INTO products (code, description) VALUES ('LIV1069', 'The Name of the Wind - Patrick Rothfuss');
INSERT INTO products (code, description) VALUES ('LIV1070', 'The Wise Man s Fear - Patrick Rothfuss');
INSERT INTO products (code, description) VALUES ('LIV1071', 'The Final Empire - Brandon Sanderson');
INSERT INTO products (code, description) VALUES ('LIV1072', 'Words of Radiance - Brandon Sanderson');
INSERT INTO products (code, description) VALUES ('LIV1073', 'The Way of Kings - Brandon Sanderson');
INSERT INTO products (code, description) VALUES ('LIV1074', 'Elantris - Brandon Sanderson');
INSERT INTO products (code, description) VALUES ('LIV1075', 'Warbreaker - Brandon Sanderson');
INSERT INTO products (code, description) VALUES ('LIV1076', 'The Martian - Andy Weir');
INSERT INTO products (code, description) VALUES ('LIV1077', 'Project Hail Mary - Andy Weir');
INSERT INTO products (code, description) VALUES ('LIV1078', 'Ready Player One - Ernest Cline');
INSERT INTO products (code, description) VALUES ('LIV1079', 'Armada - Ernest Cline');
INSERT INTO products (code, description) VALUES ('LIV1080', 'Dune - Frank Herbert');
INSERT INTO products (code, description) VALUES ('LIV1081', 'Foundation - Isaac Asimov');
INSERT INTO products (code, description) VALUES ('LIV1082', 'I, Robot - Isaac Asimov');
INSERT INTO products (code, description) VALUES ('LIV1083', 'Enders Game - Orson Scott Card');
INSERT INTO products (code, description) VALUES ('LIV1084', 'Neuromancer - William Gibson');
INSERT INTO products (code, description) VALUES ('LIV1085', 'Snow Crash - Neal Stephenson');
INSERT INTO products (code, description) VALUES ('LIV1086', 'Cryptonomicon - Neal Stephenson');
INSERT INTO products (code, description) VALUES ('LIV1087', 'The Hunger Games - Suzanne Collins');
INSERT INTO products (code, description) VALUES ('LIV1088', 'Catching Fire - Suzanne Collins');
INSERT INTO products (code, description) VALUES ('LIV1089', 'Mockingjay - Suzanne Collins');
INSERT INTO products (code, description) VALUES ('LIV1090', 'Divergent - Veronica Roth');
INSERT INTO products (code, description) VALUES ('LIV1091', 'Insurgent - Veronica Roth');
INSERT INTO products (code, description) VALUES ('LIV1092', 'Allegiant - Veronica Roth');
INSERT INTO products (code, description) VALUES ('LIV1093', 'The Giver - Lois Lowry');
INSERT INTO products (code, description) VALUES ('LIV1094', 'The Maze Runner - James Dashner');
INSERT INTO products (code, description) VALUES ('LIV1095', 'Scythe - Neal Shusterman');
INSERT INTO products (code, description) VALUES ('LIV1096', 'Thunderhead - Neal Shusterman');
INSERT INTO products (code, description) VALUES ('LIV1097', 'The Toll - Neal Shusterman');
INSERT INTO products (code, description) VALUES ('LIV1098', 'The Secret History - Donna Tartt');
INSERT INTO products (code, description) VALUES ('LIV1099', 'The Goldfinch - Donna Tartt');
INSERT INTO products (code, description) VALUES ('LIV1100', 'Normal People - Sally Rooney');